package dev.tally.http;

/**
 * The machine error codes and the HTTP status each maps to.
 */
public enum ErrorCode {
    MALFORMED_JSON(400), BODY_NOT_OBJECT(400),
    NAME_REQUIRED(400), NAME_LENGTH(400), NAME_CHARSET(400),
    OPENING_BALANCE_NOT_INTEGER(400), OPENING_BALANCE_NEGATIVE(400), OPENING_BALANCE_TOO_LARGE(400),
    FROM_ACCOUNT_ID_REQUIRED(400), TO_ACCOUNT_ID_REQUIRED(400),
    FROM_ACCOUNT_ID_INVALID(400), TO_ACCOUNT_ID_INVALID(400),
    AMOUNT_REQUIRED(400), AMOUNT_NOT_INTEGER(400), AMOUNT_NOT_POSITIVE(400), AMOUNT_TOO_LARGE(400),
    SAME_ACCOUNT(400), UNKNOWN_FIELD(400),
    INVALID_LIMIT(400), INVALID_CURSOR(400), EVENT_TIME_INVALID(400),
    IDEMPOTENCY_KEY_MISSING(400), IDEMPOTENCY_KEY_INVALID(400), IDEMPOTENCY_KEY_CONFLICT(409),
    AUTH_MISSING(401), AUTH_INVALID(401),
    UNKNOWN_ACCOUNT(422), INSUFFICIENT_FUNDS(422), RESERVED_ACCOUNT(422),
    ACCOUNT_NOT_FOUND(404), NOT_FOUND(404),
    METHOD_NOT_ALLOWED(405), BODY_TOO_LARGE(413), RATE_LIMITED(429), INTERNAL(500);

    public final int status;

    ErrorCode(int status) {
        this.status = status;
    }
}
